name: Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Lint Code Base
        uses: super-linter/super-linter@v8.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main

          VALIDATE_SNAKEMAKE_SNAKEFMT: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_YAML_PRETTIER: true

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: styler

      - name: Check R style
        run: Rscript -e 'changed <- styler::style_dir(".", dry = "on"); if (any(changed$changed)) quit(status = 1)'
